version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  logstash_log:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config_log:/etc/logstash/conf.d
    ports:
      - "5001:5001"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/etc/kibana/
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  rundeck:
    build: rundeck/
    volumes:
      - ./rundeck/plugins/:/opt/rundeck-plugins
      - ./rundeck/config/:/etc/rundeck/
    ports:
      - 4440:4440
    environment:
      - SERVER_URL=http://localhost:4440
    networks:
      - docker_elk

networks:
  docker_elk:
    driver: bridge
